### PR TITLE
Added bisection method and a test for it.

### PR DESCRIPTION
**Pull request by Madoxen**
Also wrote Signum template method in grad.h. 

If something is wrong with code formatting let me know.

### CODE REVIEW

**Comment by Madoxen** [comment]
I resolved merge conflict, merged everything together, nothing was lost.

**Comment by sudz123** [comment]
A few changes I would like :
- Comments should be inside the function, you can check the other functions
- You have evaluated `obj_func((x1+x2)/2)` for termination criteria, however what we need to evaluate is the gradient value. You can check Newton Raphson method for how to use the gradient functions defined in `grad.h`
- `grad.h` is only meant for gradient functions such as Jacobian, Hessian etc. Maybe you can move the sgn template to `util.h` for now.

Once add these I will merge your PR. It's great to see that you have understood most of the code :)
After merging, I will make some tiny formatting changes, do take a look for future PRs.

**Comment by Madoxen** [comment]
All right I will try to fix as fast as possible

**Comment by Madoxen** [comment]
Ok first of all, sorry for being late with this PR but I needed to do my uni stuff first and second if I understood gradients correctly, a gradient of a single-variable function is just it's derivative... but our Derivative function returns a Vector/Set of two variables. I dont quite understand what they mean (those two variables)...

**Comment by Madoxen** [comment]
Never mind, i get it! The "a" component is single derivative, and the "b" component is second derivative. I will add this statement to function comment.

**Comment by sudz123** [comment]
Yup that's right. Sorry I was late to review this. Great work understanding the algorithm and implementing it. Although the format is slightly different than the rest of the code, but I think it works well !

**Pull request merged**
