### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by vinnyA3**
* Made raw git link modification to README
* Unignore documentation build files
* Added build development environment

### CODE REVIEW

**Comment by sudz123** [comment]
@vinnyA3 The next step would be to add the following : 

- A header like : 
screen shot 2018-10-29 at 10 32 18 pm
- A side bar like : 
screen shot 2018-10-29 at 10 33 31 pm

**Comment by sudz123** [comment]
The components can be changed accordingly. For starters lets have the :
- " How to install Optimizer"
- A simple first program in the form of `test.cpp` which is in tests.

**Comment by vinnyA3** [comment]
@sudz123 Sounds good!  I'll get started tomorrow when I can.

**Comment by sudz123** [comment]
Great!

**Pull request merged**
